f = open("krushna.txt")
print(f.tell())
print(f.readline())
print("Before seek function :",f.tell())
f.seek(13)
print("After seek function :",f.tell())
print(f.readline())
print(f.tell())
f.close()